keypress_delay_ms: 10

# `modmap` section
# For key-to-key remapping (no combinations). Remapping a key to a modifier key (e.g. CapsLock to Control_L) is supported only in `modmap` section
modmap:
  - name: Make âŒ˜ act as Ctrl
    #    application:
    #      not: [org.gnome.Terminal, org.gnome.Console]
    remap:
      KEY_LEFTCTRL: KEY_LEFTMETA
      KEY_LEFTMETA: KEY_LEFTCTRL
      # KEY_CAPSLOCK: # macOS style CapsLock
      #   held: KEY_CAPSLOCK
      #   alone: [KEY_RIGHTMETA, KEY_SPACE]
      #   alone_timeout_millis: 200

# `keymap` section
# For remapping a sequence of key combinations to another sequence of key combinations
keymap:
  - name: Terminal copy and paste and window management
    application:
      only: Gnome-terminal
    remap:
      Ctrl-C: Shift-Super-C
      Ctrl-V: Shift-Super-V
      Ctrl-T: Shift-Super-T
      Ctrl-N: Shift-Super-N
      Ctrl-W: Shift-Super-W
      Ctrl-Q: Shift-Super-Q
      Ctrl-F: Shift-Super-F
  - name: Terminal and Console interrupt
    application:
      only: [Gnome-terminal, org.gnome.Console, org.gnome.Ptyxis]
    remap:
      Super-C: Ctrl-C

  - name: Console and Ptyxis shortcuts
    application:
      only: [org.gnome.Console, org.gnome.Ptyxis]
    remap:
      Ctrl-C: Ctrl-Shift-C # Copy text
      Ctrl-V: Ctrl-Shift-V # Paste text
      Ctrl-N: Ctrl-Shift-N # New window
      Ctrl-Q: Ctrl-Shift-Q # Close window
      Ctrl-T: Ctrl-Shift-T # New tab
      Ctrl-W: Ctrl-Shift-W # Close tab
      Ctrl-F: Shift-Ctrl-F # Find
